nocalhost/nocalhost-vscode-plugin

- src/main/commands/ExecCommand.ts
- src/main/commands/PortForwardCommand.ts
- src/main/ctl/nhctl.ts
- src/main/host.ts
- src/main/nodes/AppNode.ts
adapte port-forward and terminal
> adapte to windows

- package.nls.json
fix #121
fix this url in plugin
> fix deprecated url

- src/main/commands/InstallAppSourceCommand.ts
https://codingcorp.coding.net/p/nocalhost/bug-tracking/issues/1879/detail
> install quick demo add installing status

- src/main/commands/InstallAppSourceCommand.ts
support deploy demo from coding.net
> fix: github is not available

- src/main/commands/OpenProjectCommand.ts
> fix: open project reopen window

- scripts/createUpgradePackage.js
- src/main/ctl/nhctl/cli.ts
- src/main/utils/download.ts
> fix: Nhctl is deleted when nhctl download fails

- src/main/ctl/shell.ts
- src/main/host.ts
> fix: gbk garbled code under some systems

- src/main/clusters/AccountCluster.ts
- src/main/debug/nocalhost/start.ts
- src/main/nodes/NocalhostRootNode.ts
> fix: Nocalhost debug won't start after cluster renaming

- src/main/commands/UninstallCommand.ts
> fix: unistall app data tree node not found

- src/main/utils/index.ts
> fix: Do not show cluster when server api fails

- .github/workflows/build.yml
- src/main/ctl/nhctl/cli.ts
> fix: associate-queryer is empty when there are spaces in the directory

- package.json
- src/main/commands/CleanPvcCommand.ts
- src/main/ctl/nhctl/cli.ts
- src/main/nodes/customerResources/CrdFolder.ts
- src/main/nodes/interfact.ts
> fix: crd and workload clear pvc

- package.nls.json
- package.nls.zh-cn.json
> style: Update start proxy mode name 

- src/main/debug/provider/IDebugProvider.ts
- src/main/debug/provider/index.ts
- src/main/debug/provider/pythonDebugProvider.ts
> feat: Support for multiple versions of Python

- src/main/nodes/workloads/KubernetesResourceDevMode.ts
- src/main/nodes/workloads/controllerResources/job/Job.ts
> fix: crd resources do not have status

- package.json
> fix: Open project is not available

- .github/workflows/release.yml
fix: duplicate build script variables VERSION
> Fix: duplicate build script variables VERSION

- .github/workflows/release.yml
> chore: Change vsce publishing script

- scripts/prebuild.js
> Fix incorrect version

- src/main/clusters/AccountCluster.ts
- src/main/nodes/KubeConfigNode.ts
> style: Modify no cluster prompt

- src/main/state.ts
> fix: del log

- src/main/nodes/NocalhostRootNode.ts
> style: Remove server password log

- src/main/extension.ts
> style: When Terminal is open, do not open nocalhost output

- .github/workflows/ui-test.yml
> test: Update ui test script

- src/main/component/syncManage/command.ts
- src/main/ctl/nhctl/cli.ts
- src/main/ctl/nhctl/type.ts
- test/extension/integration/devMode.js
- test/extension/lib/components/terminal.js
> feat: add param nid

- .github/workflows/release.yml
- .vscodeignore
Signed-off-by: zhangjian <1018zhangjian@gmail.com>
> chore: Update release job

- src/main/commands/sync/OpenSyncCommand.ts
- src/main/commands/sync/SyncServiceCommand.ts
> fix: Cannot click on statusBar without devmode enabled

- src/main/commands/RunCommand.ts
- src/main/debug/liveReload.ts
> fix: Hot reload are invalid under remote run
